RMX2170: Bypass build time check for users-libs
FAILED: out/target/product/RMX2170/obj/APPS/RealmeParts_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/product/RMX2170/obj/APPS/RealmeParts_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/product/RMX2170/obj/APPS/RealmeParts_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bin/aapt2 	   	   	   	   	  out/target/common/obj/APPS/RealmeParts_intermediates/manifest/AndroidManifest.xml )"
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (out/target/common/obj/APPS/RealmeParts_intermediates/manifest/AndroidManifest.xml):
		<uses-library android:name="androidx.window.extensions" android:required="false"/>
		<uses-library android:name="androidx.window.sidecar" android:required="false"/>

note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- for details, see build/make/Changes.md and https://source.android.com/devices/tech/dalvik/art-class-loader-context

Signed-off-by: BalayBera <balaybera@proton.me>